CREATE SCHEMA IF NOT EXISTS bronze;

DROP TABLE IF EXISTS bronze."EKET" CASCADE;
CREATE TABLE bronze."EKET" (
    MANDT TEXT,
    EBELN TEXT,
    EBELP TEXT,
    ETENR TEXT,
    EINDT TEXT,
    SLFDT TEXT,
    MENGE TEXT,
    WEMNG TEXT,
    WEDAT TEXT,
    GLMNG TEXT,
    BANFN TEXT,
    BNFPO TEXT
);

DROP TABLE IF EXISTS bronze."EKKO" CASCADE;
CREATE TABLE bronze."EKKO" (
    MANDT TEXT,
    EBELN TEXT,
    BUKRS TEXT,
    BSART TEXT,
    LIFNR TEXT,
    EKORG TEXT,
    EKGRP TEXT,
    BEDAT TEXT,
    WAERS TEXT
);

DROP TABLE IF EXISTS bronze."EKPO" CASCADE;
CREATE TABLE bronze."EKPO" (
    MANDT TEXT,
    EBELN TEXT,
    EBELP TEXT,
    MATNR TEXT,
    MENGE TEXT,
    MEINS TEXT,
    NETPR TEXT,
    PEINH TEXT,
    WERKS TEXT,
    EINDT TEXT,
    ELIKZ TEXT
);

DROP TABLE IF EXISTS bronze."EQUK" CASCADE;
CREATE TABLE bronze."EQUK" (
    MANDT TEXT,
    MATNR TEXT,
    WERKS TEXT,
    QUNUM TEXT,
    VDATU TEXT,
    BDATU TEXT,
    SCMNG TEXT,
    ERDAT TEXT,
    ERNAM TEXT
);

DROP TABLE IF EXISTS bronze."EQUP" CASCADE;
CREATE TABLE bronze."EQUP" (
    MANDT TEXT,
    QUNUM TEXT,
    QUPOS TEXT,
    BESKZ TEXT,
    LIFNR TEXT,
    BEWRK TEXT,
    QUOTE TEXT,
    QUBMG TEXT,
    QUMNG TEXT,
    MAXMG TEXT,
    MINLS TEXT,
    MAXLS TEXT,
    PLIFZ TEXT,
    PREIH TEXT,
    VERID TEXT
);

DROP TABLE IF EXISTS bronze."KNA1" CASCADE;
CREATE TABLE bronze."KNA1" (
    MANDT TEXT,
    KUNNR TEXT,
    LAND1 TEXT,
    NAME1 TEXT,
    ORT01 TEXT,
    PSTLZ TEXT,
    REGIO TEXT,
    KTOKD TEXT,
    ERDAT TEXT
);

DROP TABLE IF EXISTS bronze."LFA1" CASCADE;
CREATE TABLE bronze."LFA1" (
    MANDT TEXT,
    LIFNR TEXT,
    LAND1 TEXT,
    NAME1 TEXT,
    ORT01 TEXT,
    PSTLZ TEXT,
    REGIO TEXT,
    KTOKK TEXT,
    STCD1 TEXT,
    ERDAT TEXT,
    ERNAM TEXT,
    SPERR TEXT,
    XCPDK TEXT
);

DROP TABLE IF EXISTS bronze."LIKP" CASCADE;
CREATE TABLE bronze."LIKP" (
    MANDT TEXT,
    VBELN TEXT,
    LFART TEXT,
    BLDAT TEXT,
    WADAT TEXT,
    WADAT_IST TEXT,
    KODAT TEXT,
    LADDT TEXT,
    TDDAT TEXT,
    KUNNR TEXT,
    KUNAG TEXT,
    VKORG TEXT,
    VSTEL TEXT,
    ROUTE TEXT,
    INCO1 TEXT,
    BTGEW TEXT,
    GEWEI TEXT
);

DROP TABLE IF EXISTS bronze."LIPS" CASCADE;
CREATE TABLE bronze."LIPS" (
    MANDT TEXT,
    VBELN TEXT,
    POSNR TEXT,
    MATNR TEXT,
    LFIMG TEXT,
    LGMNG TEXT,
    VRKME TEXT,
    WERKS TEXT,
    LGORT TEXT,
    CHARG TEXT,
    VGBEL TEXT,
    VGPOS TEXT,
    WBSTA TEXT,
    PSTYV TEXT,
    NTGEW TEXT,
    BRGEW TEXT
);

DROP TABLE IF EXISTS bronze."MARA" CASCADE;
CREATE TABLE bronze."MARA" (
    MANDT TEXT,
    MATNR TEXT,
    MTART TEXT,
    MBRSH TEXT,
    MATKL TEXT,
    MEINS TEXT,
    BRGEW TEXT,
    GEWEI TEXT,
    ERSDA TEXT
);

DROP TABLE IF EXISTS bronze."MARC" CASCADE;
CREATE TABLE bronze."MARC" (
    MANDT TEXT,
    MATNR TEXT,
    WERKS TEXT,
    EKGRP TEXT,
    DISMM TEXT,
    DISLS TEXT,
    MINBE TEXT,
    EISBE TEXT,
    MABST TEXT,
    BESKZ TEXT,
    SOBSL TEXT,
    PLIFZ TEXT,
    WEBAZ TEXT,
    DZEIT TEXT,
    LGPRO TEXT,
    LGFSB TEXT,
    MMSTA TEXT
);

DROP TABLE IF EXISTS bronze."MARD" CASCADE;
CREATE TABLE bronze."MARD" (
    MANDT TEXT,
    MATNR TEXT,
    WERKS TEXT,
    LGORT TEXT,
    LABST TEXT,
    UMLME TEXT,
    INSME TEXT,
    EINME TEXT,
    SPEME TEXT,
    RETME TEXT,
    LFGJA TEXT,
    LFMON TEXT
);

DROP TABLE IF EXISTS bronze."RESB" CASCADE;
CREATE TABLE bronze."RESB" (
    MANDT TEXT,
    RSNUM TEXT,
    RSPOS TEXT,
    RSART TEXT,
    MATNR TEXT,
    WERKS TEXT,
    LGORT TEXT,
    BDMNG TEXT,
    ENMNG TEXT,
    MEINS TEXT,
    BDDAT TEXT,
    AUFNR TEXT,
    VBELN TEXT,
    KZEAR TEXT
);

DROP TABLE IF EXISTS bronze."T001W" CASCADE;
CREATE TABLE bronze."T001W" (
    MANDT TEXT,
    WERKS TEXT,
    NAME1 TEXT,
    BWKEY TEXT,
    LAND1 TEXT,
    REGIO TEXT,
    ORT01 TEXT,
    FABKL TEXT,
    EKORG TEXT,
    VKORG TEXT,
    KUNNR TEXT,
    LIFNR TEXT
);

DROP TABLE IF EXISTS bronze."TFACT" CASCADE;
CREATE TABLE bronze."TFACT" (
    MANDT TEXT,
    IDENT TEXT,
    SPRAS TEXT,
    LTEXT TEXT
);

DROP TABLE IF EXISTS bronze."VBAK" CASCADE;
CREATE TABLE bronze."VBAK" (
    MANDT TEXT,
    VBELN TEXT,
    ERDAT TEXT,
    ERZET TEXT,
    ERNAM TEXT,
    AUART TEXT,
    KUNNR TEXT,
    NETWR TEXT,
    WAERK TEXT,
    VKORG TEXT,
    VTWEG TEXT,
    SPART TEXT,
    GBSTK TEXT
);

DROP TABLE IF EXISTS bronze."VBAP" CASCADE;
CREATE TABLE bronze."VBAP" (
    MANDT TEXT,
    VBELN TEXT,
    POSNR TEXT,
    MATNR TEXT,
    MENGE TEXT,
    MEINS TEXT,
    NETWR TEXT,
    WAERK TEXT,
    WERKS TEXT,
    LGORT TEXT,
    PSTYV TEXT,
    ABGRU TEXT
);

DROP TABLE IF EXISTS bronze."VBBE" CASCADE;
CREATE TABLE bronze."VBBE" (
    MANDT TEXT,
    MATNR TEXT,
    WERKS TEXT,
    LGORT TEXT,
    BDART TEXT,
    VBELN TEXT,
    POSNR TEXT,
    BDMNG TEXT,
    MEINS TEXT,
    BDDAT TEXT,
    AEDAT TEXT
);

DROP TABLE IF EXISTS bronze."VBUP" CASCADE;
CREATE TABLE bronze."VBUP" (
    MANDT TEXT,
    VBELN TEXT,
    POSNR TEXT,
    GBSTA TEXT,
    ABSTK TEXT,
    WBSTK TEXT,
    FKSTK TEXT,
    LVSTK TEXT,
    LSSTK TEXT,
    KOSTA TEXT,
    LFGSK TEXT
);
